//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyorder
    {
        public buyorder()
        {
            this.installations = new HashSet<installation>();
            this.orderlines = new HashSet<orderline>();
        }
    
        public int order_ID { get; set; }
        public int customer_ID { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<int> delivery_ID { get; set; }
        public Nullable<int> installation_ID { get; set; }
        public float total_price { get; set; }
    
        public virtual delivery delivery { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<installation> installations { get; set; }
        public virtual ICollection<orderline> orderlines { get; set; }
    }
}
