//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class betterlimitedEntities : DbContext
    {
        public betterlimitedEntities()
            : base("name=betterlimitedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<buyorder> buyorders { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<defect> defects { get; set; }
        public DbSet<delivery> deliveries { get; set; }
        public DbSet<delivery_assignment> delivery_assignment { get; set; }
        public DbSet<delivery_type> delivery_type { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<good_received> good_received { get; set; }
        public DbSet<installation> installations { get; set; }
        public DbSet<installation_assignment> installation_assignment { get; set; }
        public DbSet<orderline> orderlines { get; set; }
        public DbSet<position> positions { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<purchase_orderline> purchase_orderline { get; set; }
        public DbSet<purchaseorder> purchaseorders { get; set; }
        public DbSet<reorder> reorders { get; set; }
        public DbSet<replenishment> replenishments { get; set; }
        public DbSet<replenishment_product> replenishment_product { get; set; }
        public DbSet<reservation> reservations { get; set; }
        public DbSet<resetpassword_request> resetpassword_request { get; set; }
        public DbSet<retail_store> retail_store { get; set; }
        public DbSet<retail_store_product> retail_store_product { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<warehouse> warehouses { get; set; }
        public DbSet<warehouse_product> warehouse_product { get; set; }
        public DbSet<worker> workers { get; set; }
    }
}
