//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_type
    {
        public delivery_type()
        {
            this.deliveries = new HashSet<delivery>();
        }
    
        public int deliveryTypeID { get; set; }
        public string deliveryTypeName { get; set; }
    
        public virtual ICollection<delivery> deliveries { get; set; }
    }
}
