//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_assignment
    {
        public int assignment_ID { get; set; }
        public int delivery_ID { get; set; }
        public int worker_ID { get; set; }
    
        public virtual delivery delivery { get; set; }
        public virtual worker worker { get; set; }
    }
}
