//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public delivery()
        {
            this.buyorders = new HashSet<buyorder>();
            this.defects = new HashSet<defect>();
            this.delivery_assignment = new HashSet<delivery_assignment>();
            this.installations = new HashSet<installation>();
        }
    
        public int delivery_ID { get; set; }
        public int type { get; set; }
        public string status { get; set; }
        public float net_weight { get; set; }
        public Nullable<System.DateTime> approve_time { get; set; }
        public Nullable<System.DateTime> complete_time { get; set; }
        public Nullable<int> assignment_ID { get; set; }
        public System.DateTime delivery_date { get; set; }
    
        public virtual ICollection<buyorder> buyorders { get; set; }
        public virtual ICollection<defect> defects { get; set; }
        public virtual ICollection<delivery_assignment> delivery_assignment { get; set; }
        public virtual delivery_type delivery_type { get; set; }
        public virtual ICollection<installation> installations { get; set; }
        public virtual replenishment replenishment { get; set; }
    }
}
