//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.staffs = new HashSet<staff>();
            this.positions = new HashSet<position>();
        }
    
        public int department_ID { get; set; }
        public string department_name { get; set; }
        public Nullable<int> department_head { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<position> positions { get; set; }
    }
}
