//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public position()
        {
            this.staffs = new HashSet<staff>();
            this.workers = new HashSet<worker>();
        }
    
        public int positionID { get; set; }
        public string position_title { get; set; }
        public float min_salarly { get; set; }
        public float max_salary { get; set; }
        public Nullable<int> department_ID { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<worker> workers { get; set; }
        public virtual department department { get; set; }
    }
}
