//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.defects = new HashSet<defect>();
            this.orderlines = new HashSet<orderline>();
            this.purchase_orderline = new HashSet<purchase_orderline>();
            this.replenishment_product = new HashSet<replenishment_product>();
            this.reservations = new HashSet<reservation>();
            this.retail_store_product = new HashSet<retail_store_product>();
            this.warehouse_product = new HashSet<warehouse_product>();
        }
    
        public int product_ID { get; set; }
        public string name { get; set; }
        public int category_ID { get; set; }
        public int supplier_ID { get; set; }
        public int phaseout_stat { get; set; }
        public int restock_level { get; set; }
        public int irestock_level { get; set; }
        public float price { get; set; }
        public float weight { get; set; }
        public string dimension { get; set; }
        public byte[] product_image { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<defect> defects { get; set; }
        public virtual ICollection<orderline> orderlines { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual ICollection<purchase_orderline> purchase_orderline { get; set; }
        public virtual ICollection<replenishment_product> replenishment_product { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual ICollection<retail_store_product> retail_store_product { get; set; }
        public virtual ICollection<warehouse_product> warehouse_product { get; set; }
    }
}
