//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseorder
    {
        public purchaseorder()
        {
            this.purchase_orderline = new HashSet<purchase_orderline>();
        }
    
        public int purchase_order_ID { get; set; }
        public int supplier_ID { get; set; }
        public string status { get; set; }
        public float total { get; set; }
        public int reorder_ID { get; set; }
        public System.DateTime creation_time { get; set; }
        public Nullable<System.DateTime> approve_time { get; set; }
    
        public virtual ICollection<purchase_orderline> purchase_orderline { get; set; }
        public virtual reorder reorder { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
