//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseorder
    {
        public purchaseorder()
        {
            this.reorders = new HashSet<reorder>();
        }
    
        public int purchase_order_ID { get; set; }
        public int sent_by { get; set; }
        public int supplier_ID { get; set; }
        public float total { get; set; }
        public string invoice_link { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual ICollection<reorder> reorders { get; set; }
    }
}
