//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class reorder
    {
        public int reorder_ID { get; set; }
        public int sender_ID { get; set; }
        public int receiver_ID { get; set; }
        public int warehouse_ID { get; set; }
        public int purchase_order_ID { get; set; }
    
        public virtual purchaseorder purchaseorder { get; set; }
        public virtual warehouse warehouse { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
