//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class retail_store
    {
        public retail_store()
        {
            this.replenishments = new HashSet<replenishment>();
            this.retail_store_product = new HashSet<retail_store_product>();
        }
    
        public int store_ID { get; set; }
        public string address { get; set; }
        public int contact_number { get; set; }
        public System.TimeSpan opening_hour { get; set; }
        public System.TimeSpan closing_hour { get; set; }
        public string contact_email { get; set; }
        public int manager { get; set; }
    
        public virtual ICollection<replenishment> replenishments { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<retail_store_product> retail_store_product { get; set; }
    }
}
