//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.purchaseorders = new HashSet<purchaseorder>();
            this.reorders = new HashSet<reorder>();
            this.reorders1 = new HashSet<reorder>();
            this.replenishments = new HashSet<replenishment>();
            this.retail_store = new HashSet<retail_store>();
            this.warehouses = new HashSet<warehouse>();
        }
    
        public int staff_ID { get; set; }
        public string name { get; set; }
        public int phone_no { get; set; }
        public string email { get; set; }
        public int position_ID { get; set; }
        public int department_ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime hire_date { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual department department { get; set; }
        public virtual position position { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
        public virtual ICollection<reorder> reorders { get; set; }
        public virtual ICollection<reorder> reorders1 { get; set; }
        public virtual ICollection<replenishment> replenishments { get; set; }
        public virtual ICollection<retail_store> retail_store { get; set; }
        public virtual ICollection<warehouse> warehouses { get; set; }
    }
}
