//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.products = new HashSet<product>();
            this.purchaseorders = new HashSet<purchaseorder>();
        }
    
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
    }
}
