//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public warehouse()
        {
            this.reorders = new HashSet<reorder>();
            this.warehouse_product = new HashSet<warehouse_product>();
        }
    
        public int warehouse_ID { get; set; }
        public string address { get; set; }
        public int zip_code { get; set; }
        public int warehouse_head { get; set; }
    
        public virtual ICollection<reorder> reorders { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<warehouse_product> warehouse_product { get; set; }
    }
}
