//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimitedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public worker()
        {
            this.delivery_assignment = new HashSet<delivery_assignment>();
        }
    
        public int worker_ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int work_type { get; set; }
        public System.DateTime hire_date { get; set; }
        public System.DateTime DOB { get; set; }
        public int phone_no { get; set; }
    
        public virtual ICollection<delivery_assignment> delivery_assignment { get; set; }
        public virtual position position { get; set; }
    }
}
